baseURL = 'https://commentathor.de/'
languageCode = 'de'
defaultContentLanguage = 'de'
title = 'Commentathor'
theme = 'cactus'
copyright = 'Thorsten Schwesig'

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  colortheme = "white"
  rss = true
  description = "Comment-a-Thor - a blog by @schwesig"
  mainSection = "posts"
  showAllPostsOnHomePage = false
  postsOnHomePage = 10
  tagsOverview = true
  dateFormat = "02.01.2006"
  showReadTime = true

  [[params.social]]
    name = "github"
    link = "https://github.com/schwesig"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Beiträge"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "Kategorien"
  url = "/categories"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 5
