baseURL = 'https://commentathor.de/'
languageCode = 'de'
defaultContentLanguage = 'de'
title = 'Commentathor'
theme = 'terminal'

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.de]
    title = "Commentathor"
    subtitle = "Comment-a-Thor - a blog by @schwesig"
    keywords = "blog, zitate, quotes"
    copyright = "Thorsten Schwesig"
    menuMore = "Mehr zeigen"
    readMore = "Weiterlesen"
    readOtherPosts = "Andere Beiträge"

    [languages.de.params.logo]
      logoText = "Commentathor"
      logoHomeLink = "/"

    [[languages.de.menu.main]]
      identifier = "posts"
      name = "Beiträge"
      url = "/posts"
    [[languages.de.menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags"
    [[languages.de.menu.main]]
      identifier = "categories"
      name = "Kategorien"
      url = "/categories"
    [[languages.de.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
